### PR TITLE
Add bloop

### PR DESCRIPTION
**Pull request by alexarchambault**

### CODE REVIEW

**Comment by alexarchambault** [comment]
cc @jvican

At some point, this could build a graalvm launcher for that, or even download a prebuilt one.

**Comment by jvican** [comment]
This is awesome, thanks a lot! :heart:

**Comment by jvican** [comment]
Hey @alexarchambault I'm going to be working on publishing the binaries to have bloop be installed mainly via `coursier`. However, we currently don't have a binary for Windows, while we do have binaries for macOS and Linux. How will coursier behave in this case?
  
What I'd like is that coursier fallsback on the JVM download descriptor if the download of a binary for a given platform doesn't work. I haven't tried this, so I don't know if coursier already behaves this way.

**Comment by alexarchambault** [comment]
As of now, if an app has `"launcherType": "graalvm-native-image"`, it will either download the [prebuilt launcher](https://github.com/coursier/apps/blob/7f821c78ad2806d3470e96e2659643fddbef5474/apps/resources/cs.json#L11) if it's available, else try to build the binary itself.

I agree it'd be better if we could use the prebuilt version if it's there, else fallback on a JVM launcher… I opened https://github.com/coursier/coursier/issues/1628 to remember it, with a description of the changes required for that.

**Pull request merged**
