### PR TITLE
Updating guardrail

### PR DESCRIPTION
**Pull request by blast-hardcheese**
- Organization change
- New module system

Thank you!

### CODE REVIEW

**Review by alexarchambault — COMMENTED** [review]
Thanks!

One remark though: having several `latest.*` versions doesn't work well. If users specify an explicit version, like `cs install --contrib guardrail:X.Y.Z`, the explicit version will only apply to the first module, not the others.

Isn't there really a way to have a single module pull all the others?

**Comment by blast-hardcheese** [comment]
> is there a way to have one module pull in all the others?

So, each module is versioned independently because the version numbers just became completely irrelevant or useless after we started supporting more than a few targets, so ideally they would be independently discovered by coursier, using normal eviction rules (as we use MiMa to ensure compatibility).

I do recognize your point about explicit version setting though, I hadn't considered that.

Absolute worst case, I can just have an explicit module only for coursier that depends on everything and autoreleases any time the build passes, though even then the version number is completely disconnected from reality, defeating the purpose of the ability to manually set version numbers.

I don't think having a distinct guardrail runner per leaf dependency would work either, as we would already have 6, it would be unpleasant for the user to have so much noise to dig through. (Also that the modules are designed to work together, if you have however many there are, you can use them all on the same CLI.

I'm kind of at a loss, do you have any guidance here?

**Comment by blast-hardcheese** [comment]
Alright. Sorry to leave this open for so long untended, I've done as you suggested -- `guardrail-all` has now just been published.

Thank you for your patience, and for such a fantastic tool.

**Review by alexarchambault — APPROVED** [review]
Great that it's a single module again!

**Pull request merged**
