### PR TITLE
Update README only upon release

### PR DESCRIPTION
**Pull request by alexarchambault**

### CODE REVIEW

**Comment by alexarchambault** [comment]
cc @ckipp01 

I'll see how it goes when tagging `0.0.19`.

**Comment by ckipp01** [comment]
> cc @ckipp01
> 
> I'll see how it goes when tagging `0.0.19`.

Sounds good. 😬

**Comment by alexarchambault** [comment]
Mmmhh, seems [that didn't work either](https://travis-ci.org/github/coursier/apps/jobs/680242160#L237):
```bash
Skipping a deployment with the pages provider because this branch is not permitted: v0.0.20
```

**Comment by alexarchambault** [comment]
Seems we'll have to resort to [this hack](https://stackoverflow.com/a/48959539/3714539).

**Comment by ckipp01** [comment]
I mean one other option would be to just remove it from Travis and move it to github actions. It's much easier to manage something like this there imo. The rest of the other stuff can just stay on Travis, but the script and updating the repo can be done via Actions. We do that in a few of our Scalameta projects and haven't had issues. However I also get if you want to only stick with Travis.

**Comment by alexarchambault** [comment]
It's even for me. I've been wanting to use `deploy` in `.travis.yml` in other contexts, I'm ok debugging it here a bit…

**Comment by alexarchambault** [comment]
@regadas's [channel template](https://github.com/regadas/coursier-channel.g8) uses Actions. Maybe we could switch to that here too, and even maybe add the README-updating logic to the template.

**Comment by regadas** [comment]
@alexarchambault sounds good! I can take a look at this tmr.

**Pull request merged**
