### PR TITLE
Possible recommendation to fix Scala installation

### PR DESCRIPTION
**Pull request by bishabosha**
Edit: I tested this now

fixes https://github.com/coursier/apps/issues/238

### CODE REVIEW

**Comment by bishabosha** [comment]
With the second commit this is working locally - so now by default (i.e. the latest stable) it will look for the prebuilt binary on GitHub, but for any requested explicit version less than 3.5.0-RC1 its going to install the traditional way

**Review by Gedochao — APPROVED** [review]

**Comment by tgodzik** [comment]
I think this should work with the need for 3.5.0 suffix, no?

**Review by tgodzik — APPROVED** [review]

**Comment by tgodzik** [comment]
Thanks Jamie!

**Comment by bjornregnell** [comment]
> I think this should work with the need for 3.5.0 suffix, no?

Yes I hope when this fix is out suffix should not be needed. But in the meantime and if people alreade have the downloaded thing for somehow in a chache or whatever the warning might resurrect and itmaybe doesn't hurt to say the workaorund... But it depends how long it takes for the fix to get to users.

**Pull request merged**
