### PR TITLE
Add catscript

### PR DESCRIPTION
**Pull request by ChristopherDavenport**
If I understand right this would allow 

`cs install catscript`

Catscript is a scripting tool that's generally useful directly for scala. Hence this channel, similar to ammonite.

https://github.com/davenverse/catscript

### CODE REVIEW

**Review by alexarchambault — COMMENTED** [review]
@ChristopherDavenport I think it'd be a better fit for the contrib channel for now… The main channel is for tools that already have some traction, or that are somehow "officially" recommended. Whereas we basically accept anything that can be pulled from Central in the contrib channel.

**Comment by alexarchambault** [comment]
That would change the command above to
```text
$ cs install --contrib catscript
```

**Comment by ChristopherDavenport** [comment]
File has been moved.

**Comment by ChristopherDavenport** [comment]
What is the criteria for promotion from contrib to the main channel? So I can watch out for what traction I might have that would warrant such a request in the future.

**Comment by alexarchambault** [comment]
These things aren't set in stone yet, but I'd say as soon as something fits the criteria above, it can be moved there.

**Review by alexarchambault — APPROVED** [review]

**Pull request merged**
