### PR TITLE
Add seed to main channel

### PR DESCRIPTION
**Pull request by alexarchambault**

### CODE REVIEW

**Comment by alexarchambault** [comment]
cc @tindzk

With this, users can run seed with
```bash
$ cs launch seed
```
or install it with
```bash
$ cs install seed
```

You can also create bootstraps with
```bash
$ cs bootstrap seed -o seed
```

You can also replace `seed` with `seed:X.Y.Z` to install or start a specific version, like
```bash
$ cs launch seed:0.1.7
$ cs bootstrap seed:0.1.7 -o seed
```

**Comment by alexarchambault** [comment]
The README of seed states
> Note that we use Bloop's version of Coursier. This is to avoid incompatibilities because Seed itself relies on Coursier and its version would be overridden by the launcher otherwise.

I think bloop doesn't ship with `blp-coursier` any more, or does it? I hope it's not a problem any more to use whatever coursier launcher users have.

**Comment by tindzk** [comment]
Thanks for adding Seed! I will update the documentation once this has been merged.

You are right. Bloop does not ship with Coursier anymore. However, the issue the README was referring to is that the Coursier launcher made `coursier._` available on the classpath. When Seed used a different Coursier version, it would cause exceptions. Would it be possible for Coursier to run all programs with an empty classpath?

**Comment by alexarchambault** [comment]
> However, the issue the README was referring to is that the Coursier launcher made coursier._ available on the classpath.

It shouldn't. Bootstraps can leak things under [`coursier.bootstrap.launcher`](https://github.com/coursier/coursier/tree/966a98def18ee9af2799982ed56e44cf533bb7d0/modules/bootstrap-launcher/src/main/java/coursier/bootstrap/launcher), but it shouldn't conflict with anything I guess. coursier itself, used as a library, doesn't put things in that namespace in particular.

**Comment by alexarchambault** [comment]
Merging then, don't hesitate to report if anything doesn't work as expected down the line.

**Comment by tindzk** [comment]
> It shouldn't. Bootstraps can leak things under [`coursier.bootstrap.launcher`](https://github.com/coursier/coursier/tree/966a98def18ee9af2799982ed56e44cf533bb7d0/modules/bootstrap-launcher/src/main/java/coursier/bootstrap/launcher), but it shouldn't conflict with anything I guess. coursier itself, used as a library, doesn't put things in that namespace in particular. So the launched apps can use any coursier version.

Thanks for clarifying! This might have changed in a recent version. I tried launching Seed (which depends on Coursier 1.1.0) with `cs` and did not encounter any class exception this time. If the problem reappears, I will make sure to open an issue.

**Pull request merged**
