### PR TITLE
Bump up version of dotty repl

### PR DESCRIPTION
**Pull request by ckipp01**

### CODE REVIEW

**Comment by alexarchambault** [comment]
I'm getting an error when trying that locally:
```text
$ cs launch --default-channels=false --channel ./apps/resources dotty-repl
Resolution error: Error downloading ch.epfl.lamp:dotty-compiler_0.28:latest.stable
  not found: ~/.ivy2/local/ch.epfl.lamp/dotty-compiler_0.28
  No latest stable version found in https://repo1.maven.org/maven2/ch/epfl/lamp/dotty-compiler_0.28/maven-metadata.xml
```

It seems `0.26` works. Unless we should use nightly? (`latest.stable` -> `latest.release`)

**Comment by ckipp01** [comment]
Ach, sorry total oversight on my part, and I totally glossed over the `stable`. Yea we can probably just stay with `.26:latest.stable` unless you think otherwise.

**Comment by eloots** [comment]
I hadn't seen this PR when before I created #72 . Instead of going for _0.26.0_, I would suggest to go for _0.27.0-RC1_ (as this will become _0.27.0_ soon anyway).

Thanks @ckipp01 for #71 ! Very handy.

**Comment by alexarchambault** [comment]
I'd say it's safer to stay on `latest.stable`, as dotty releases are cut automatically

**Comment by alexarchambault** [comment]
Merging, thanks!

**Pull request merged**
